cupon/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('cupon-list/', views.cupon_list, name='cupon-list'),
    path('cupon-list/<minimum>/', views.cupon_min, name='cupon-min'),
    path('search/', views.search, name='search'),
    path('get-cupon-list/', views.get_cupon_minim, name='minimum-spending'),
    path('get-cupons/', views.get_cupons, name='iterating-all-cupons'),
]

groupassignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from authentication import views as authentication_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('onlineshop.urls', 'onlineshop'), namespace="onlineshop")),
    path('', include(('cupon.urls', 'cupon'), namespace="cupon")),
    path('', include(('shoppingbag.urls', 'shoppingbag'), namespace="shoppingbag")),
    path('', include('social_django.urls', namespace='social')),
    path('register/', authentication_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

onlineshop/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<slug>/', views.ItemDetail.as_view(), name='item'),
    path('product/<slug>/add-review/', views.add_review, name='add-review'),
    path('category/<slug>/', views.CatProductList.as_view(), name='cat_product'),
    path('add-transaction/', views.add_to_transaction, name='add-transaction'),
    path('transactions/', views.trans, name = 'transactions'),
]

shoppingbag/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('add-to-bag/', views.add_to_bag, name='add-bag'),
    path('shopping-bag/', views.shopping_bag, name='shopping-bag'),
    path('modify-bag/', views.modify_bag, name='modify-bag'),
]

onlineshop/models.py
from django.db import models
from cupon.models import Cupon
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=50, null=False)
    slug = models.SlugField(max_length=70, unique=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    stock = models.IntegerField()
    description = models.TextField()
    slug = models.SlugField(max_length=70, unique=True)

    def __str__(self):
        return self.name

class Transaction(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    cupon = models.ForeignKey(Cupon, on_delete=models.CASCADE, null=True)
    total =  models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.buyer.username

class Review(models.Model):
    revname = models.CharField(max_length = 50, null = False)
    star = models.IntegerField()
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    message = models.CharField(max_length = 300, null =False)
    datecreated = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.revname

class TransactionItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=False)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, null=False)
    quantity = models.IntegerField(default=1)

onlineshop/forms.py
from django import forms
from onlineshop.models import (
    Category,
    Item,
    Transaction,
    Review,
)
from cupon.models import Cupon

class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = ('buyer', 'cupon', 'total')

onlineshop/views.py
from django.shortcuts import (
    render,
    HttpResponse,
    get_object_or_404,
    redirect,
)
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views import generic
from onlineshop.models import (
    Category,
    Item,
    TransactionItem,
    Transaction,
    Review,
)
from cupon.models import Cupon
from .forms import (
    TransactionForm
)

def index(request):
    category_all = Category.objects.all()
    response = {
        'categories': category_all,
    }
    return render(request, 'index.html', response)

@login_required
def trans(request):
    trans = ()
    transaction = Transaction.objects.filter(buyer = request.user)
    for t in transaction:
        items = ()
        for ti in TransactionItem.objects.filter(transaction=t):
            items += ((ti.item.name, ti.quantity),)
        trans += ((t, items),)
    categories = Category.objects.all()
    response = {
        'transactions': trans,
        'categories': categories,
    }
    return render(request, 'transactions.html', response)

class CatProductList(generic.ListView):
    template_name = 'productlist.html'
    context_object_name = 'items'

    def get_queryset(self):
        cat = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Item.objects.filter(category = cat)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        context['categories'] = Category.objects.all()
        return context

class ItemDetail(generic.DetailView):
    model = Item
    template_name = 'product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        this_item = get_object_or_404(Item, slug=self.kwargs.get('slug'))
        context['reviews'] = Review.objects.filter(item=this_item.id)
        context['categories'] = Category.objects.all()
        return context

def add_review(request, *args, **kwargs):
    this_item = Item.objects.get(slug=kwargs.get('slug'))
    if request.method == 'POST':
        rev_name = request.POST.get('revname', None)
        rev_msg = request.POST.get('revmsg', None)
        rev_star = int(request.POST.get('star', None))
        new_rev = Review(revname=rev_name, star=rev_star, item=this_item, message=rev_msg)
        new_rev.save()
        return redirect('onlineshop:item', slug=this_item.slug)
    return render(request, 'index.html')

@login_required
def add_to_transaction(request):
    if request.method == 'POST':
        user = request.user
        total = request.POST['total']
        try:
            coupon = Cupon.objects.get(code=request.POST['cupon'])
            new_transaction = Transaction.objects.create(buyer=user, cupon=coupon, total=total)
        except:
            coupon = 0
            new_transaction = Transaction.objects.create(buyer=user, total=total)
        items = []
        for i in request.session['cart']:
            item = Item.objects.get(slug=i[0])
            if (item.stock < i[1]):
                new_transaction.delete()
                json = {
                    "success": False,
                    "transmsg": "There are {} {} left in stock!".format(item.stock, item.name),
                }
                return JsonResponse(json, safe=False)
            items.append((item, i[1]))
        for i in items:
            TransactionItem.objects.create(item=i[0], transaction=new_transaction, quantity=i[1])
            i[0].stock -= i[1]
            i[0].save()
        request.session['cart'] = []
        json = {
            "success": True,
            "transmsg": "Transaction has been successful!",
        }
        return JsonResponse(json, safe=False)

onlineshop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'onlineshop/css/styles.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'onlineshop/css/main-custom.css' %}" />
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	{% block head-plus %}
	{% endblock head-plus %}
</head>

<body>
	<div class="main" style="overflow-y: hidden;">

		<!-- Content goes here -->
		{% block content %}
		{% endblock content %}

		<!-- TOP NAVBAR FROM HERE -->
		<div class="navbar-top">
			<center>
				<h1><b> F R É O N E </b></h1>
				<br /><br />
				{% for cat in categories %}
					<a href="{% url 'onlineshop:cat_product' cat.slug %}">{{ cat.name }}</a>
				{% endfor %}
			</center>
		</div>
		<div class="input-group">
			<div class="row">
				<div class="col-6">
					<form method="POST" class="post-form" action="{% url 'cupon:search' %}">
						{% csrf_token %}
						<div class="form-row">
							<div class="form-group col-md-12">
								<input type="text" name="text_search" class="form-control" placeholder="Search" aria-label="Text input with dropdown button">
								<input type="hidden" name="options" value="coupon" />
							</div>
						</div>
					</form>
				</div>
				<div class="col-2">
					<a href="{% url 'login' %}"><i class="fa fa-user-circle fa-2x facust-bag" aria-hidden="true"></i></a>
				</div>
				<div class="col-2">
					<a href="{% url 'onlineshop:transactions' %}"><i class="fa fa-list-alt fa-2x facust-bag" aria-hidden="true"></i></a>
				</div>
				<div class="col-2">
					<a href="{% url 'shoppingbag:shopping-bag' %}"><i class="fa fa-shopping-bag fa-2x facust-bag" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
	</div>
	<!--TO HERE-->

	</div>
</body>

</html>

onlineshop/templates/cupon-list.html
{% extends "second-base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Coupons</title>
{% endblock head-plus %}

<!-- Page Content -->
{% block content %}
<div class="container" style="margin-top:1rem;">
  <div class="row">
    <h1>COUPONS</h1>
  </div>
  {% for cupon in cupons %}
    {% if forloop.first %}<div class="row">{% endif %}
      <div class="col-4 cupon-list">
        <div class="card">
          <div class="card-header">
            {{ cupon.get_percent }}%
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ cupon.code }}</h5>
            <p class="card-text">Minimum IDR {{ cupon.minimum }}</p>
          </div>
        </div>
      </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
  {% endfor %}
</div>


{% endblock content %}

onlineshop/templates/index.html
{% extends "base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Freone</title>
{% endblock head-plus %}

<!-- Page Content -->
{% block content %}
<div id="carouselControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'onlineshop/images/product-1-wallpaper.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'onlineshop/images/product-2-wallpaper.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'onlineshop/images/product-1.jpg' %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev car-ctrl" href="#carouselControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next car-ctrl" href="#carouselControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="text-center" style="margin-left:-20rem">
  <center><button type="button" class="btn btn-dark btn-custom">SHOP THIS LOOK</button></center>

</div>

{% endblock content %}

onlineshop/templates/main-page.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Freone</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC:400,700&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link type="text/css" rel="stylesheet" href="{% static 'onlineshop/css/main-custom.css' %}"/>
	</head>
	<body>
		<div class="main">
			<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">
					<div class="carousel-item active">
						<img class="d-block w-100" src="{% static 'onlineshop/images/product-1-wallpaper.jpg' %}" alt="First slide">
					</div>
					<div class="carousel-item">
						<img class="d-block w-100" src="{% static 'onlineshop/images/product-2-wallpaper.jpg' %}" alt="Second slide">
					</div>
					<div class="carousel-item">
						<img class="d-block w-100" src="{% static 'onlineshop/images/product-1.jpg' %}" alt="Third slide">
					</div>
				</div>
				<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
			<button type="button" class="btn btn-dark btn-custom">SHOP THIS LOOK</button>
			
			<!-- TOP NAVBAR -- FROM HERE -->
			<div class="navbar-top">
				<center>
					<h1><b> F  R  É  O  N  E </b></h1>
					<br/><br/>
					<a href="#">MEN</a>
					<a href="#">WOMEN</a>
					<a href="#">YOUTH</a>
				</center>
			</div>
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Search" aria-label="Text input with dropdown button">
				<div class="input-group-append">
					<button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Category</button>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="#">MEN</a>
						<a class="dropdown-item" href="#">WOMEN</a>
						<a class="dropdown-item" href="#">YOUTH</a>
						<div role="separator" class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">ALL</a>
					</div>
				</div>
			</div>
			<!--TO HERE-->
		</div>
		

		
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	</body>
</html>

onlineshop/templates/product.html
{% extends "second-base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Product Name</title>
{% endblock head-plus %}

<!-- Page Content -->
{% block content %}
<div class="container">
  <div class="row prod-div">
    <div class="col-md-5 text-center">
      <img src="{% static 'onlineshop/images/sc-med-2.jpg' %}" />
    </div>
    <div class="col-md-7">
      <div class="prod-text-box">
        <div class="prod-text">
          <h2>{{ object.name }}</h2>
          <h4>IDR {{ object.price }}</h4>
        </div>
        <div class="prod-text">
          <p>{{ object.description }}</p>
        </div>
      </div>
      {% if user.is_authenticated %}
        <div class="prod-btn">
          <input type="hidden" name="item-slug" id="item-slug" value="{{ object.slug }}">
          <button type="submit" class="btn btn-outline-dark" id="add-to-bag">ADD TO BAG</button>
        </div>
      {% else %}
        <div class="prod-btn">
          <input type="hidden" name="item-slug" id="item-slug" value="{{ object.slug }}">
          <button type="submit" class="btn btn-outline-dark disabled" id="add-to-bag" disabled>ADD TO BAG</button>
          <p class="text-muted">Please login</p>
        </div>
      {% endif %}
      <div id="add-bag-status"></div>
    </div>
  </div>
  <br />
  <div class="row prod-div">
    <div class="col-md-5 text-center">
      <img src="{% static 'onlineshop/images/sc-med-2.jpg' %}" />
    </div>
    <div class="col-md-7">
      <div class="rev-text-box">
        <div class="rev-text">
          <h2>Review</h2>
        </div>
        {% for review in reviews %}
          <div class="rev-detail">
            <div class="row">
              <div class="col-3 text-center">
                <img src="{% static 'onlineshop/images/stat-crop.jpg' %}"/>
              </div>
              <div class="col-9 rev-full">
                <div class="row">
                  <div class="col-6">
                    <div class="text-left rev-star">
                      {% with ''|center:review.star as range %}
                      {% for i in range %}
                        <i class="fa fa-star" aria-hidden="true"></i>
                      {% endfor %}
                      {% endwith %}
                    </div>
                  </div>
                  <div class="col-6">
                    <div class="rev-name text-right">
                      <h3>{{ review.revname }}</h3>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col- text-left rev-info">
                    <p>{{ review.message }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        <h3>Leave a review</h3>
        <form method="POST" class="post-form" action="{% url 'onlineshop:add-review' object.slug %}">
        {% csrf_token %}
          <div class="row" style="max-width: 450px; margin: auto; margin-bottom: 4vh;">
            <input type="text" class="form-control" placeholder="Enter name" name="revname"><br>
            <input type="text" class="form-control" placeholder="Enter message" name="revmsg">
            <select class="form-control" name="star">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary">Add Review</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% csrf_token %}
<script src="{% static 'shoppingbag/js/shoppingbag.js' %}"></script>
<script>
  var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
      }
  });
  $('#add-to-bag').on('click', function(){
    var input = $("#item-slug").val();
    var api_url = "{% url 'shoppingbag:add-bag' %}";

    $.post({
      url: api_url,
      data: {slug: input},
      success: function(res) {
        var msg = $("#add-bag-status");
        if (res.success) {
          var alert_msg =
            '<div class="alert alert-success" role="alert">' +
            res.bagmsg +
            '</div>';
        } else {
          var alert_msg =
            '<div class="alert alert-danger" role="alert">' +
            res.bagmsg +
            '</div>';
        }
        msg.html(alert_msg);
      }
    })
  });
</script>
{% endblock content %}

onlineshop/templates/productlist.html
{% extends "second-base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Product List</title>
{% endblock head-plus %}

<!-- Page Content -->
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="big-picture text-right">
        <p><img src="{% static 'onlineshop/images/1.png' %}" alt="catalogue1" style="width:560px;border:0;"></p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="category-title text-left">
        <p style="font-size:64px;margin:0">{{ category.name }}</p>
      </div>
    </div>
  </div>
  <div class="row" style="margin-top: 10vh">
  </div>
  {% for item in items %}
    {% if forloop.first %}<div class="row prod-list">{% endif %}
      <div class="col-md-4">
        <a href="{% url 'onlineshop:item' item.slug %}">
        <div class="cat-picture text-center">
          <p><img src="{% static 'onlineshop/images/stephanie-nakagawa-ADSKIn0ScDg-unsplash.jpg' %}" alt="cat1" style="width:280px;border:0;margin-bottom:0;padding-bottom:0">
          <p style="font-size:30px;padding-top:0px;margin-bottom:0;padding-bottom:0">{{ item.name }}</p>
          <p style="font-size:24px;padding-top:0px;margin-bottom:0;padding-bottom:0">{{ item.price }}</p>
        </div>
        </a>
      </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
  {% endfor %}
</div>
{% endblock content %}

onlineshop/templates/second-base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'onlineshop/css/styles.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'onlineshop/css/main-custom.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'shoppingbag/css/style.css' %}">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static "shoppingbag/js/shoppingbag.js" %}"></script>
	<script type="text/javascript" src="{% static "shoppingbag/js/shoppingbag-btn.js" %}"></script>
	{% block head-plus %}
	{% endblock head-plus %}
</head>

<body>
	<div class="main">

		<!-- TOP NAVBAR FROM HERE -->
		<div class="nav-custom mb-5">
			<div class="navbar-top-2" style="">
				<center>
					<h1><b> F R É O N E </b></h1>
					<br /><br />
					{% for cat in categories %}
						<a href="{% url 'onlineshop:cat_product' cat.slug %}">{{ cat.name }}</a>
					{% endfor %}
				</center>
			</div>
			<div class="input-group">
				<div class="row">
					<div class="col-6">
						<form method="POST" class="post-form" action="{% url 'cupon:search' %}">
							{% csrf_token %}
							<div class="form-row">
								<div class="form-group col-md-12">
									<input type="text" name="text_search" class="form-control" placeholder="Search" aria-label="Text input with dropdown button">
									<input type="hidden" name="options" value="coupon" />
								</div>
							</div>
						</form>
					</div>
					<div class="col-2">
						<a href="{% url 'login' %}"><i class="fa fa-user-circle fa-2x facust-bag" aria-hidden="true"></i></a>
					</div>
					<div class="col-2">
						<a href="{% url 'onlineshop:transactions' %}"><i class="fa fa-list-alt fa-2x facust-bag" aria-hidden="true"></i></a>
					</div>
					<div class="col-2">
						<a href="{% url 'shoppingbag:shopping-bag' %}"><i class="fa fa-shopping-bag fa-2x facust-bag" aria-hidden="true"></i></a>
					</div>
				</div>
			</div>
		</div>
		<!--TO HERE-->

		<!-- Content goes here -->
		{% block content %}
		{% endblock content %}

	</div>
</body>

</html>

onlineshop/templates/transactions.html
{% extends "second-base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Transactions</title>
{% endblock head-plus %}

<!-- Page Content -->
{% block content %}
<div class="container">
  <div class="row ml-5">
    <h3>YOUR TRANSACTIONS</h3>
  </div>
  {% for trans in transactions %}
    {% if forloop.first %}<div class="row prod-list">{% endif %}
      <div class="card col-4" style="width: 15rem;">
        <div class="card-body" style="border: 3px solid #000; margin: 2rem 2rem 2rem 2rem;">
          <h5 class="card-title">Items</h5>
          {% for item in trans.1 %}
            <p class="card-text">{{ item.0 }} x {{ item.1 }}</p>
          {% endfor %}
          {% if trans.0.cupon.code %}
            <h5 class="card-title">Coupon</h5>
            <p class="card-text">{{ trans.0.cupon.code }}</p>
          {% endif %}
          <h5 class="card-title">Total</h5>
          <p class="card-text">IDR {{ trans.0.total }}</p>
        </div>
      </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row prod-list">{% endif %}
    {% if forloop.last %}</div>{% endif %}
  {% empty %}
  <div class="row mt-4 ml-5">
    <div class="alert alert-info" role="alert">
      You have not made any transactions yet!
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}