cupon/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('cupon-list/', views.cupon_list, name='cupon-list'),
    path('cupon-list/<minimum>/', views.cupon_min, name='cupon-min'),
    path('search/', views.search, name='search'),
    path('get-cupon-list/', views.get_cupon_minim, name='minimum-spending'),
    path('get-cupons/', views.get_cupons, name='iterating-all-cupons'),
]

groupassignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from authentication import views as authentication_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('onlineshop.urls', 'onlineshop'), namespace="onlineshop")),
    path('', include(('cupon.urls', 'cupon'), namespace="cupon")),
    path('', include(('shoppingbag.urls', 'shoppingbag'), namespace="shoppingbag")),
    path('', include('social_django.urls', namespace='social')),
    path('register/', authentication_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

onlineshop/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<slug>/', views.ItemDetail.as_view(), name='item'),
    path('product/<slug>/add-review/', views.add_review, name='add-review'),
    path('category/<slug>/', views.CatProductList.as_view(), name='cat_product'),
    path('add-transaction/', views.add_to_transaction, name='add-transaction'),
    path('transactions/', views.trans, name = 'transactions'),
]

shoppingbag/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('add-to-bag/', views.add_to_bag, name='add-bag'),
    path('shopping-bag/', views.shopping_bag, name='shopping-bag'),
    path('modify-bag/', views.modify_bag, name='modify-bag'),
]

shoppingbag/models.py
from django.db import models

# Create your models here.

shoppingbag/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from onlineshop.models import (
    Category,
    Item,
)

@login_required
def add_to_bag(request):
    if request.method == 'POST':
        this_item = request.POST['slug']
        try:
            if 'cart' in request.session:
                cart = request.session['cart']
                item_exist = False
                for item in cart:
                    if item[0] == this_item:
                        item[1] += 1
                        item_exist = True
                if not item_exist:
                    cart.append((this_item, 1))
                request.session['cart'] = cart
            else:
                request.session['cart'] = []
                cart = request.session['cart']
                cart.append((this_item, 1))
                request.session['cart'] = cart
            json = {
                "success": True,
                "bagmsg": "Successfully added to shopping bag!",
            }
            return JsonResponse(json, safe=False)
        except:
            json = {
                "success": False,
                "bagmsg": "An error occured!",
            }
            return JsonResponse(json, safe=False)

@login_required
def shopping_bag(request):
    items = []
    if 'cart' in request.session.keys():
        cart = request.session['cart']
        for c in cart:
            items.append((Item.objects.get(slug=c[0]), c[1]))
    else:
        response = {
            'empty': True,
            'items': None,
            'total': 0,
            'categories': Category.objects.all(),
        }
        return render(request, "shopping-bag.html", response)
    total = 0
    for item in items:
        total += item[0].price * item[1]
    request.session['base_price'] = total
    response = {
        'empty': False,
        'items': items,
        'total': total,
        'categories': Category.objects.all(),
    }
    return render(request, "shopping-bag.html", response)

def modify_bag(request):
    item = Item.objects.get(name=request.GET['name']).slug
    qty = request.GET['qty']
    new_total = request.GET['new-price']
    type = request.GET['type']
    cart = request.session['cart']
    if type == 'remove':
        for c in cart:
            if c[0] == item:
                cart.remove(c)
    else:
        for c in cart:
            if c[0] == item:
                c[1] = int(qty)
    request.session['base_price'] = new_total
    json = {
        "item": item,
        "qty": qty,
        "new_price": new_total,
        "type": type,
    }
    if not cart:
        json["empty"] = "true"
    else:
        json["empty"] = "false"
    return JsonResponse(json, safe=False)

shoppingbag/templates/shopping-bag.html
{% extends "second-base.html" %}
{% load static %}
{% csrf_token %}

<!-- Head -->
{% block head-plus %}
<title>Your Bag!</title>
{% endblock head-plus %}

<!-- Page Content -->
{% block content %}
<div class="container bag-custom">
  <div class="row ml-5">
    <h3>YOUR BAG</h3>
  </div>
  {% if not empty %}
    {% for item in items %}
    <div class="row mt-3">
      <div class="col-lg-4 col-md-6 col-sm-6">
        <img src="{% static 'onlineshop/images/ian-dooley-wzRKn-AjKf4-unsplash.jpg' %}" class="img-fluid" alt="" style="height: 250px; width: auto;">
      </div>
      <div class="col-lg-8 col-md-6 col-sm-6 text-left">
          <div class="prod-text-trans" style="margin-top:1rem; margin-bottom: 2rem">
            <h2 id="item-name">{{ item.0.name }}</h2>
            <h3>IDR <span id="item-price">{{ item.0.price }}</span></h3>
            <h5>QTY: <span id="item-qty">{{ item.1 }}</span></h5>
            <span>
              <button class="btn-inc" id="btn-inc"><i class="fa fa-plus"></i></button>
              <button class="btn-dec" id="btn-dec"><i class="fa fa-minus"></i></button>
              <button class="btn-rm" id="btn-rm"><i class="fa fa-trash"></i></button>
            </span>
          </div>
      </div>
    </div>
    {% endfor %}
  {% else %}
    <div class="row mt-4 ml-5">
      <div class="alert alert-info" role="alert">
        You have not added items to the bag yet!
      </div>
    </div>
  {% endif %}

  <div class="row mt-5 ml-5">
    <div class="col-lg-8 col-md-6 col-sm-6 text-left">
      <div class="form-group">
        <div class="form-group autocomplete">
          <label for="InputName">Coupon</label>
          <input type="text" name="input_coupon" class="form-control" placeholder="Insert Coupon" id="coupon-code-input">
        </div>
        <button type="button" id="submit-button"> submit </button><br>
        <input type="radio" id="radio-code" name="name" value="code" checked />
        <label for="code">search by code</label>
        <input  class="ml-5" type="radio" id="radio-discount" name="name" value="discount">
        <label for="discount">search by discount percentage</label><br>
      </div>
    </div>
  </div>


  <div class="row text-left ml-5">
    <div class="col-7">
      <h3 style="margin-left: 0rem;width:400px">Total : IDR <span id="base-price">{{ total }}</span></h3>
    </div>
  </div>
  <div class="row text-left ml-5">
    <div class="col-7">
      <h3 style="margin-top:1rem; margin-left:0rem;;width:400px">Discounted: IDR <span id="total-disc">0</span></h3>
    </div>
  </div>
  <div class="row text-left ml-5">
    <div class="col-9">
      <h3 style="margin-top:1rem; margin-left:0rem;max-width:650px">Amount to be Paid: IDR <span id="final-amount">{{ total }}</span></h3>
    </div>
    <div class="col-3">
      <button type="submit" class="btn btn-success" id="confirm-checkout" style="margin-top:1rem;width:100px;height:60px">Checkout</button>
    </div>
  </div>
  <br />
  <div id="trans-alert"></div>
</div>

<script>
  var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
  var trans_api_url = "{% url 'onlineshop:add-transaction' %}";
</script>


{% endblock content %}